[package]
name = "celestite-buffer"
version = "0.1.0"
edition = "2024"

[features]
default = []
wasm = ["dep:tsify", "dep:wasm-bindgen"]

[dependencies]
loro = { version = "=1.16.2", default-features = false }
similar = { version = "=2.7.0", default-features = false, features = ["wasm32_web_time"] }
web-time = "1.1.0"

serde = { workspace = true, features = ["derive", "rc"] }
thiserror.workspace = true
tsify = { version = "=0.5.8", default-features = false, features = ["js"], optional = true }
wasm-bindgen = { version = "=0.2.129", optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
