[package]
name = "celestite-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = []
wasm = ["celestite-buffer/wasm", "dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys", "dep:tsify"]
preview = ["dep:notist", "dep:notist-html"]

[dependencies]
celestite-buffer.workspace = true
notist = { workspace = true, optional = true }
notist-html = { workspace = true, optional = true }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
wasm-bindgen = { version = "=0.2.129", optional = true }
wasm-bindgen-futures = { version = "=0.4.79", optional = true }
js-sys = { version = "=0.3.106", optional = true }
tsify = { version = "=0.5.8", default-features = false, features = ["js"], optional = true }

[dev-dependencies]
futures-lite = "2.6.1"

[lints]
workspace = true
